export const CLIENT_CONFIG = {
  companyName: "Fencing Pro",
  companyTagline: "Corporate Boundary Designer · Interactive Suite",
  companyLegal: "2026 Fencing Pro Pty Ltd",
  primaryColor: "#f20c32",
  logoAccentColor: "#f20c32",
  marketRegion: "NSW Metropolitan",
  fencingStandard: "AS-2423 Approved",
  footerSecurityText: "AS-2423 SECURE VAULT",
  footerSystemText: "SYSTEM v4.1",
  loginFooterText: "Fencing Pro Pty Ltd © 2026. This secure visualizer environment has been custom-hardened for certified team consultants.",
  companyLegalShort: "Fencing Pro Pty Ltd",
  regionState: "NSW",
  regionCity: "Sydney",
  proposalIdPrefix: "FPRO",
  companyPhone: "0400 000 000",
  companyEmail: "info@example.com.au",
  companyWebsite: "www.example.com.au",
  companyAddress: "123 Example St, City, State 0000",
  companyABN: "00 000 000 000",
  logoFileName: "logo.png",
  quoteValidityDays: 30,
  quoteTerms: "This quote is valid for 30 days from the date of issue. All prices include GST. A 10% deposit is required to confirm booking. Final measurements will be confirmed on-site prior to installation.",
};
