export const CLIENT_CONFIG = {
  companyName: "Fencely",
  companyTagline: "Quote & Visualise · Professional Suite",
  companyLegal: "2026 Fencely",
  primaryColor: "#ff6a1f",
  logoAccentColor: "#ff6a1f",
  marketRegion: "Australia",
  fencingStandard: "AU Fencing Standards",
  footerSecurityText: "FENCELY",
  footerSystemText: "v1.0",
  loginFooterText: "Fencely © 2026. Professional fencing quote and visualisation platform for Australian fencing companies.",
  companyLegalShort: "Fencely",
  regionState: "AU",
  regionCity: "Sydney",
  proposalIdPrefix: "FNC",
  companyPhone: "0400 000 000",
  companyEmail: "info@fencely.com",
  companyWebsite: "www.fencely.com",
  companyAddress: "",
  companyABN: "",
  logoFileName: "logo.png",
  quoteValidityDays: 30,
  quoteTerms: "This quote is valid for 30 days from the date of issue. All prices include GST. A 10% deposit is required to confirm booking. Final measurements will be confirmed on-site prior to installation.",
};
